version: '3.7'

services:
  imapapi:
    image: 'talentsconnect/imapapi:${DOCKER_TAG:-latest}'
    build: '.'
    restart: always
    environment: 
      REDIS_URL: 'redis://redis:6379'
      API_HOST: '0.0.0.0'
    ports:
      - 3000:3000
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: 'redis:buster'
    restart: always